Diverse oppgaver Kristoffer
vtfk/component-library pull request #299
Opened 2022-01-26 08:46 UTC by ksundmyhr

- La til mulighet for hint tekst under TextField
- PersonCard komponent
- Switch komponent
- Lagt til ny komponent Illustration med nye ikoner (mer illustrative enn "vanlige" ikoner, derav ny komponent)

-----

![Skjermbilde 2022-01-26 kl  09 43 21](https://user-images.githubusercontent.com/1224930/151131173-59f12e76-7240-4de2-96f7-530de2279e1e.png)

![Skjermbilde 2022-01-26 kl  09 43 33](https://user-images.githubusercontent.com/1224930/151131178-ec03acee-27db-465e-bbd3-ec2be7034274.png)

![Skjermbilde 2022-01-26 kl  09 43 45](https://user-images.githubusercontent.com/1224930/151131180-5d615653-e8c8-4695-8f93-1f7b3f1436e2.png)

![Skjermbilde 2022-01-26 kl  09 43 03](https://user-images.githubusercontent.com/1224930/151131165-00789af1-15da-416e-ae7c-c88ae1218141.png)

2022-01-26 08:49 UTC, ksundmyhr commented on src/ui/Illustration/Illustration.stories.js
> +          */
Det er noe muffins med mobility-ikonet. Så det må sannsynligvis eksporteres som SVG på nytt fra designer.

2022-01-26 09:45 UTC, runely requested changes

2022-01-26 09:45 UTC, runely commented on src/ui/Illustration/index.js
> +  name: PropTypes.string.isRequired,
Kanskje brukt `PropTypes.oneOf([ 'work', 'outdoors', ...]).isRequired` isteden så hvilke valg man har kommer ut i dokumetasjonen

2022-01-26 09:45 UTC, runely commented on src/ui/TextField/index.js
> +export function TextField ({ type, className, placeholder, value, id, disabled, noBorder, rows, rounded, onFocus, onBlur, error, inputRef, hintTextOnFocus, ...props }) {
Legge til `hintTextOnFocus` i PropTypes så det kommer ut i dokumetasjonen

2022-02-02 12:55 UTC, runely commented on src/ui/Illustration/index.js
> +  name: PropTypes.string.isRequired,
Byttet til `PropTypes.oneOf([ 'work', 'outdoors', ...]).isRequired`

2022-02-02 13:09 UTC, runely commented on src/ui/TextField/index.js
> +export function TextField ({ type, className, placeholder, value, id, disabled, noBorder, rows, rounded, onFocus, onBlur, error, inputRef, hintTextOnFocus, ...props }) {
Lagt til `hintTextOnFocus` i PropTypes

2022-02-02 14:20 UTC, runely approved these changes

2022-02-02 14:21 UTC, merged